### ISSUE TITLE
Use UI states for person status

### ISSUE THREAD

**Issue by rwdnnz** [SondreNjaastad/person-card#3]
This is not really an issue, but more of a request...

I really like the look of this card and it looks like it will have great potential (would be great if it was available is HACS). I've just had a play with it and it would look much nicer if the status in the card used the UI text for home and not_home (i.e. Home and Away).

**Comment by CykloneFij** [comment]
I second the request above for HACS install!
Also, are you planning on updating and including actions on tap, etc?
Cheers and thanks for a nice implementation!

**Comment by SondreNjaastad** [comment]
All good suggestions, and something that should be done. After starting this project, I have started both parental leave and a bachelor thesis, so I'm gonna need some help from the community to get this done anytime soon. Thanks for the input!
