### ISSUE TITLE
Card not showing in lovelace

### ISSUE THREAD

**Issue by RoboMagus** [SondreNjaastad/person-card#5]
I've been fiddling around with a nice way to display person related entities in lovelace until I came accros this card.
Looks like a nice addition to my setup, however I cannot get it to work propperly.

I have the latest person-card.js located at /config/www/person-card/person-card.js, and it is included in my resources:
``` yaml
- url: /local/person-card/person-card.js
  type: module
```

In my dashboard view I've included the following:
```yaml
  - type: custom:person-card
    person: person.myself
    entities:
      - sensor.phone_presence
```

Through chrome's developer tools I can see that person-card.js is actually loaded, but the card itself remains empty in the html elements view:
```html
<div class="column">
  <person-card>
    #shadow-root (open)
  </person-card>
  ...
</div>
```

Later on I found the console also showing errors:
```
person-card.js:431 Uncaught (in promise) TypeError: Cannot read property 'attributes' of undefined
    at HTMLElement.render (person-card.js:431)
    at HTMLElement.update (person-card.js:187)
    at HTMLElement.performUpdate (person-card.js:148)
    at HTMLElement._enqueueUpdate (person-card.js:148)
```

Could there be an issue with the script not populating the card, or is there some configuration issue on my end?

**Comment by SondreNjaastad** [comment]
There definetly can, i never manage to complete it before i became a father and started writing my Bachelors degree. So if anyone want to continue to fix bugs and polish this, i Will add them as colab on this repo 😊

**Comment by RoboMagus** [comment]
Closing stale issue
